import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Trip } from '../types';
import { formatINR } from '../utils/formatters';

export const PDFService = {
    generateTripReport: (trip: Trip) => {
        const doc = new jsPDF();

        // --- Header ---
        doc.setFontSize(22);
        doc.setTextColor(40, 40, 40);
        doc.text(trip.name, 14, 20);

        doc.setFontSize(12);
        doc.setTextColor(100, 100, 100);
        doc.text(`${trip.destination} • ${new Date(trip.startDate).toLocaleDateString()} - ${new Date(trip.endDate).toLocaleDateString()}`, 14, 28);

        doc.line(14, 32, 196, 32); // Horizontal line

        // --- Trip Stats ---
        const totalCost = trip.expenses.reduce((sum, e) => sum + e.amount, 0);

        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text(`Total Trip Cost: ${formatINR(totalCost)}`, 14, 42);
        doc.text(`Total Expenses: ${trip.expenses.length}`, 14, 49);

        // --- Expenses Table ---
        const tableBody = trip.expenses.map(e => {
            const payerName = trip.members.find(m => m.id === e.payerId)?.name || 'Unknown';
            const dateStr = new Date(e.date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short' });

            return [
                dateStr,
                e.description,
                e.category,
                payerName,
                formatINR(e.amount)
            ];
        });

        // @ts-ignore
        autoTable(doc, {
            startY: 55,
            head: [['Date', 'Description', 'Category', 'Paid By', 'Amount']],
            body: tableBody,
            headStyles: { fillColor: [79, 70, 229] }, // Indigo 600
            alternateRowStyles: { fillColor: [248, 250, 252] }, // Slate 50
            columnStyles: {
                4: { halign: 'right' }
            },
            styles: {
                font: 'helvetica',
                fontSize: 10
            }
        });

        // --- Footer ---
        // @ts-ignore
        const finalY = doc.lastAutoTable.finalY || 60;

        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text(`Generated by SplitWay • ${new Date().toLocaleString()}`, 14, finalY + 10);

        // Save
        doc.save(`${trip.name.replace(/\s+/g, '_')}_Report.pdf`);
        return true;
    }
};
