import React, { useState } from 'react';
import { PlusIcon, ChevronRightIcon } from '@heroicons/react/24/outline';
import type { Member, Expense, ExpenseCategory } from '../types';

const ExpenseForm: React.FC<{ members: Member[], onAdd: (e: Expense) => void, onCancel: () => void }> = ({ members, onAdd, onCancel }) => {
    const [desc, setDesc] = useState('');
    const [amount, setAmount] = useState('');
    const [category, setCategory] = useState<ExpenseCategory>('Food');
    const [payerId, setPayerId] = useState(members[0]?.id || '');
    const [participantIds, setParticipantIds] = useState<string[]>(members.map(m => m.id));
    const [saving, setSaving] = useState(false);

    const toggleParticipant = (id: string) => {
        setParticipantIds(prev => prev.includes(id) ? prev.filter(p => p !== id) : [...prev, id]);
    };

    const toggleAll = () => {
        if (participantIds.length === members.length) {
            setParticipantIds([]);
        } else {
            setParticipantIds(members.map(m => m.id));
        }
    };

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if (desc && amount && participantIds.length > 0) {
            setSaving(true);
            onAdd({
                id: '', // Will be generated by DB or service
                description: desc,
                amount: parseFloat(amount),
                date: new Date().toISOString(),
                category,
                payerId,
                participantIds
            });
            // Don't setSaving(false) because we unmount on success
        }
    };

    const categories: ExpenseCategory[] = ['Food', 'Drink', 'Rickshaw', 'Railway', 'Flight', 'Stay', 'Water', 'Entry Fee', 'Shopping', 'Other'];

    return (
        <div className="fixed inset-0 z-[100] flex items-end sm:items-center justify-center p-0 sm:p-4 bg-slate-900/70 backdrop-blur-md animate-in fade-in duration-500">
            <div className="bg-white w-full max-w-xl rounded-t-[40px] sm:rounded-[48px] shadow-2xl overflow-y-auto max-h-[90vh] sm:max-h-none animate-in slide-in-from-bottom-20 duration-700">
                <form onSubmit={handleSubmit} className="p-8 sm:p-10 space-y-8 pb-32 sm:pb-10">
                    <div className="flex justify-between items-center mb-4">
                        <h3 className="text-3xl font-black text-slate-900 tracking-tight">Expense Details</h3>
                        <button type="button" onClick={onCancel} className="bg-slate-100 p-3 rounded-full text-slate-400 hover:text-slate-900 transition-colors">
                            <PlusIcon className="w-7 h-7 rotate-45" />
                        </button>
                    </div>

                    <div className="space-y-6">
                        <div className="bg-slate-50 p-6 rounded-[32px] border-2 border-transparent focus-within:border-indigo-500 transition-all">
                            <label className="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Description</label>
                            <input autoFocus type="text" required className="w-full bg-transparent border-none p-0 focus:ring-0 font-black text-2xl text-slate-900 placeholder:text-slate-200" placeholder="Ex: Dinner at Thalassa" value={desc} onChange={(e) => setDesc(e.target.value)} />
                        </div>

                        <div className="grid grid-cols-2 gap-6">
                            <div className="bg-slate-50 p-6 rounded-[32px] border-2 border-transparent focus-within:border-indigo-500 transition-all">
                                <label className="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Amount (₹)</label>
                                <input type="number" required step="0.01" className="w-full bg-transparent border-none p-0 focus:ring-0 font-black text-3xl text-slate-900" placeholder="0" value={amount} onChange={(e) => setAmount(e.target.value)} />
                            </div>
                            <div className="bg-slate-50 p-6 rounded-[32px] border-2 border-transparent focus-within:border-indigo-500 transition-all">
                                <label className="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Type</label>
                                <select className="w-full bg-transparent border-none p-0 focus:ring-0 font-black text-lg text-slate-900 appearance-none" value={category} onChange={(e) => setCategory(e.target.value as ExpenseCategory)}>
                                    {categories.map(c => <option key={c} value={c}>{c}</option>)}
                                </select>
                            </div>
                        </div>

                        <div>
                            <label className="block text-[11px] font-black text-slate-400 uppercase tracking-widest mb-3">Who Footed the Bill?</label>
                            <div className="flex gap-2 overflow-x-auto py-2 no-scrollbar">
                                {members.map(m => (
                                    <button key={m.id} type="button" onClick={() => setPayerId(m.id)} className={`shrink-0 px-6 py-3 rounded-2xl text-sm font-black transition-all ${payerId === m.id ? 'bg-indigo-600 text-white shadow-xl shadow-indigo-100 scale-105' : 'bg-slate-100 text-slate-500'}`}>
                                        {m.name}
                                    </button>
                                ))}
                            </div>
                        </div>

                        <div>
                            <div className="flex justify-between items-center mb-3">
                                <label className="block text-[11px] font-black text-slate-400 uppercase tracking-widest">Split with</label>
                                <button type="button" onClick={toggleAll} className="text-[10px] font-black text-indigo-600 uppercase tracking-widest hover:bg-indigo-50 px-3 py-1 rounded-lg transition-colors">
                                    {participantIds.length === members.length ? 'Deselect All' : 'Select All'}
                                </button>
                            </div>
                            <div className="flex flex-wrap gap-3">
                                {members.map(m => (
                                    <button key={m.id} type="button" onClick={() => toggleParticipant(m.id)} className={`px-5 py-3 rounded-2xl text-sm font-black transition-all flex items-center gap-3 ${participantIds.includes(m.id) ? 'bg-slate-900 text-white shadow-xl scale-105' : 'bg-slate-50 text-slate-200 line-through'}`}>
                                        {participantIds.includes(m.id) && <ChevronRightIcon className="w-4 h-4 text-indigo-400" />}
                                        {m.name}
                                    </button>
                                ))}
                            </div>
                        </div>
                    </div>

                    <div className="pt-8 flex gap-4">
                        <button type="button" onClick={onCancel} className="flex-1 py-6 rounded-[28px] font-black text-slate-400 hover:bg-slate-50 transition-colors uppercase tracking-widest text-xs">Discard</button>
                        <button type="submit" disabled={saving} className="flex-[2] bg-indigo-600 text-white py-6 rounded-[28px] font-black text-xl shadow-2xl shadow-indigo-200 hover:scale-[1.02] active:scale-95 transition-all disabled:opacity-70">
                            {saving ? 'Saving...' : 'Save Bill'}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default ExpenseForm;
